language: node_js
node_js:
- "node"
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: prsEKZ4FN29a6u2K0R4vtXNovO6hey7DDLIpRBsyU+AssIq2ZLka+dHpNoAThyhqDKbQluNRagTBLm0R9lw9hVw3kWj8gOUNk/yP5thfFdztPys/OFe7AHJDxPB8tPzhOQCl9BqO4h1k4PDsJkwyrIGiUi6inJ2DW8QSsxwnD/5U20civ3nw/s1Up9aH/5CDnrH60hYqb4rtpmjiAXw74NT/xBGKdsd75bYkF7UljgRkAZ5XQ/Pm5akbLnlYPh8IVtjKd5YDO66xcykE0jHyeyw5JXuZUPX7XhtiJ0ll0yg8nft7USOK/91TNPmjFwcl1XxVOAaD2lqOY4M/MMkzOynzYjBlLGvZ6CDvWv4OJc1xlt+vvphjaqe7oaBW0H3Dt0+xHiMLv5j2SpUB0uWd4GYmgZ3QZXK83eNaQsoFCxxJUnyoIBdBXstCTlHI901z7g0uAAkE/+KQ8uEj1VaFilExyq0Piv7qLdhnFfXMc09y94UqaDN5CPNtPH2yJ1IU53de4yyQMkaRH3D4SuvrGR8yqd50gc8OMZYc3Yc3qpTyxWALfIZJvzYnJ05WUXRE2C3ZzmV54x59TPKIRoNen0qG4HIZb1SpfqXbOnqa/6ZLlaHdZ84DDIbos4/DxOw4Eh7CaMI1dtpG/+i3lkePL5gZ/u+l+7L7/QP7384nVjo=
